### ISSUE TITLE
Bug with clear command

### ISSUE THREAD

**Issue by jianyangg** [AY2324S1-CS2103T-T13-3/tp#141]
Upon clearing the addressbook and reinitialising the program,
there's an IndexOutOfBoundsException

**Comment by jianyangg** [comment]
Index of addressbook might not reset as well.

**Comment by jianyangg** [comment]
Might be linked to customer add command.

**Comment by juliusgambe** [comment]
Bug does not appear anymore as last updated by @jianyangg
