### ISSUE TITLE
[PE-D][Tester E] User Guide a little unintuitive

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-T13-3/tp#381]
Does not tell me how to create an account at the top of the user guide... I have to scroll through all the way down to features before I can create an account. Perhaps put it in a quick start

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: wj331/ped#1

**Comment by Gabriel4357** [comment]
fixed, review to see if its ok
