### ISSUE TITLE
[PE-D][Tester D] password and confirm password mismatch

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-T13-3/tp#384]
Error message does not reflect problem.

![image.png](https://raw.githubusercontent.com/WinstonLeonard/ped/main/files/de8a99cd-fc52-4009-b333-fbe79e1398c9.png)

Error should say passwords do not match instead of Password should do not contain...

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: WinstonLeonard/ped#1

**Comment by juliusgambe** [comment]
Add to UG - Section
