### ISSUE TITLE
[PE-D][Tester D] Cannot register account

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-T13-3/tp#385]
Tried to create a user named winston but error message shows a user named Gabriella is already created.

Cannot create an account at all.

![image.png](https://raw.githubusercontent.com/WinstonLeonard/ped/main/files/4a87eae9-e08d-4bba-98c2-d0eda32d9dad.png)

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: WinstonLeonard/ped#2

**Comment by juliusgambe** [comment]
- Add only one account can be registered to UG Features Register
