### ISSUE TITLE
[PE-D][Tester E] Bug regarding finding customers (name)

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-T13-3/tp#390]
![image.png](https://raw.githubusercontent.com/wj331/ped/main/files/b21bd916-85a7-459d-98c0-4d73473a992c.png)

When input with `customer find $(!##@&(`. Still succeeds instead of returning me an error. Names should be as much as possible alphabetical? 

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: wj331/ped#5

**Comment by juliusgambe** [comment]
- Planned Enhancement
