### ISSUE TITLE
[PE-D][Tester E] Bug for editing a customer

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-T13-3/tp#392]
Unable to edit a customer even though the input is exactly what I pasted from UserGuide. Not sure why. It says name should be alphanumeric when it is already in alphanumeric

![image.png](https://raw.githubusercontent.com/wj331/ped/main/files/dc6e6353-5ce3-48fb-b821-3732f7d102bf.png)

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: wj331/ped#6

**Comment by juliusgambe** [comment]
Dash for edit user guide is wrong 

![Screenshot 2023-11-06 at 5 12 51 PM](https://github.com/AY2324S1-CS2103T-T13-3/tp/assets/67666355/de0e32d0-97ee-4298-8048-7bd987493530)

**Comment by Gabriel4357** [comment]
fixed waiting to merge
