### ISSUE TITLE
[PE-D][Tester D] delete messes with list indexes

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-T13-3/tp#396]
![image.png](https://raw.githubusercontent.com/WinstonLeonard/ped/main/files/6a2b1a70-90eb-46ce-9e9b-748274bd8b16.png)

After deleting a customer, the indexing of the list does not update. e.g. not 1,2,3,4,5 anymore

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: WinstonLeonard/ped#3

**Comment by juliusgambe** [comment]
- Specified in UG
