### ISSUE TITLE
[PE-D][Tester E] Bug with delivery note

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-T13-3/tp#405]
![image.png](https://raw.githubusercontent.com/wj331/ped/main/files/f29daaa4-ac79-481d-b872-9f765b0103b5.png)

delivery note 100 returns invalid command format which should return invalid ID (since no such delivery exists and not because the format is wrong)

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: wj331/ped#14

**Comment by juliusgambe** [comment]
Need specify --note. Invalid bug
